name: "Production"
on:
  push:
env:
  API_URL: ${{ secrets.API_URL }}
  NEXT_PUBLIC_API_URL: ${{ secrets.API_URL }}
  NEXT_PUBLIC_APP_NAME: ${{ secrets.APP_NAME }}

jobs:
  prepare:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build dependecies image
        run: docker build . --target deps  --tag kvadra-web-deps:0.0.1 --tag kvadra-web-deps:latest

  lint:
    runs-on: self-hosted
    needs: [prepare]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/lint

  test:
    runs-on: self-hosted
    needs: [prepare]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test

  release:
    runs-on: self-hosted
    needs: [prepare, lint, test]
    steps:
      - uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_API_URL: ${{ secrets.API_URL }}
          envkey_APP_NAME: ${{ secrets.APP_NAME }}
          envkey_NEXT_PUBLIC_APP_NAME: ${{ secrets.APP_NAME }}
          envkey_NEXT_PUBLIC_API_URL: ${{ secrets.API_URL }}
          file_name: .env.production
          fail_on_empty: false
      - name: Build app image
        run: docker build . --target build --tag kvadra-web-dist:0.0.1 --tag kvadra-web-dist:latest
      - name: Build release image
        run: docker build . --target release --tag ghcr.io/pmlogist/kvadra-web:0.0.1 --tag ghcr.io/pmlogist/kvadra-web:latest
      - name: Release image
        run: docker push ghcr.io/pmlogist/kvadra-web --all-tags

  deploy:
    runs-on: self-hosted
    needs: [prepare, lint, test, release]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        env:
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
          SSH_PKEY: ${{ secrets.SSH_TEST_KEY }}
      - name: Clean dangling images
        run: docker image prune -f
